name: Cleanup on aisle 5
on:
  pull_request:
    types: [closed]

jobs:
  clean-up:
    env:
      SERVICE_NAME: test
    name: Clean up stack
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pull_request.head.ref }}"
      - run: echo "${{ format('{0}-review-{1}', env.SERVICE_NAME, github.event.number)  }}"
