name: Cleanup on aisle 5
on:
  pull_request:
    types: [closed]

jobs:
  clean-up:
    name: Clean up stack
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pull_request.head.ref }}
      - run: echo "${{ github.event.pull_request.head.ref_name }}
      - run: echo "${{ github.event.pull_request.head }}
      - id: stack_name
        run: echo "name=Something-`echo "${{ github.event.pull_request.head.ref }}" | sed 's/.*\///'`" >> $GITHUB_OUTPUT
      - name: hvaharuforgearochtalents
        run: echo ${{ steps.stack_name.outputs.name }}
