name: Cleanup on aisle 5
on:
  push:
  pull_request:
    types: [opened, synchronize, closed]

env:
  ENV: devvi

jobs:
  set_environment:
    outputs:
      my_env: ${{ steps.setenv.outputs.my_env }}
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "{version}={${GITHUB_REF#refs/tags/}}" >> $GITHUB_OUTPUT
      - name: Log the version
        run: echo "The new tag is ${{ steps.get_version.outputs.version }}"
